### ISSUE TITLE
Question  |   What are you asking for exactly?

### ISSUE THREAD

**Issue by therealOri** [hjqx/FXT#1]
Just to be clear, You are asking people to see if they can essentially re build the code and make it human readable again? To get the source code.

Or are you asking people to find the string that will be built and then executed later on? I understand it will just print a list with 2 strings in it but I am not entirely sure what it is that you are asking people to do.

I'm not to sure what "try re the src code" means. I assume "Try to read the source code" or "Try to rebuild the source code".

(I'd make this in a discussions page but one hasn't been made)

**Comment by therealOri** [comment]
I'm fairly certain f2.py is just this at it's most basic form. Not 100% confident because lambda functions are a headache but this or something similar.

```python
def function():
    return ['hjqx', 'zqh']

output = function()
print(output)
```

The strings/list seem to be hard codded into the code.

**Comment by therealOri** [comment]
In case anyone is interested in a differently formatted f2.py

```python
(*f, d) = (lambda _: list(map(chr, [r for r in range([[*f].__class__(f) for f in map(range, (0, 105))][(- 1)][(- 1)], 108, 2)])))((k := (lambda : getattr)))
((f := f.__add__([d])) and (n := (lambda r: k()('', 'join')(r))) and (f := n(f)))
((r := f) and ((f := n((lambda f, r: n(list(map(chr, [].__class__((r, f))))))((d := list(map((lambda x: (x ^ 32)), [sum(list(map((lambda g: (g * 2)), [40, 4])))])))[0], (w := (lambda q, v, f: v([(lambda : int((ord(q) ^ f[0])))()])[0])('W', bytes, (38, ((o := (lambda g, f, j: (f := k())(globals(), (lambda f, g, b: ((b[::(- 1)] + (g % 'e')) + f))('r', '%sa', 'lc'))())),))))))),))
(n := (lambda n, g: g(''.join(list(map(str, n))))))
((z := (r, f)) and (g := (lambda r, n, f: [print, getattr])))
(r, f, b) = (r := (n := (lambda : list(map((lambda *n: n[0][::(- 1)]), (lambda f, d: (x := g)(r, f, n).pop()((f % '7x'), d)('s'))('86x0sa%s0s17x0', (f := (lambda v, s, f: ''.join(list(map((lambda g: g), (f, v, s)))))((n := 'li'), 't', ''.join([c for c in 'ps'])[::(- 1)])))))))())
(((r := (r := (n := (lambda n: list(map((lambda f: 55 .__class__(f, 16)), n))))((r, b, f)))) and ((n := (lambda : map(chr, list(list(map(int, (f := list((f := map(str, r)))[::(- 1)]))))))) and (x := (lambda n: list(zip([x for x in zip(z, [].__class__(n))], [n[r] for r in range(len(n)) if ((r == 1) or (r == 2))])))))) and ((f := (lambda g: ((s := x(list(n()))) and ((e := s[0][0]) and (r := s[1][0])) and (lambda r: (r.insert(2, s[1][1]), r)[1])((v := list(map((lambda x: list(x)), (r := list(list(zip(e, r))))))[1])) and g(list(map(''.join, list(zip(e, [r[0][1], ''.join(v[1:])])))))))((v := g)(r, (n, f), b)[0])), (f := o)(g, b, r)))
```

Perhaps this is easier to work with. The last line is 100% a print statement printing the result of a function.
```python
print(func())
```

**Comment by j4127v4** [comment]
Yup sorry if i was not clear, 
So, Basically, i want you to rebuild the code and make it readable again,
With that done, you'll be able to determinate how, where and which parts of the strings are manipulated to finally get printed.

**Comment by j4127v4** [comment]
> I'm fairly certain f2.py is just this at it's most basic form. Not 100% confident because lambda functions are a headache but this or something similar.
> 
> ```python
> def function():
>     return ['hjqx', 'zqh']
> 
> output = function()
> print(output)
> ```
> 
> The strings/list seem to be hard codded into the code.

not exactly

**Comment by j4127v4** [comment]
> In case anyone is interested in a differently formatted f2.py
> 
> ```python
> (*f, d) = (lambda _: list(map(chr, [r for r in range([[*f].__class__(f) for f in map(range, (0, 105))][(- 1)][(- 1)], 108, 2)])))((k := (lambda : getattr)))
> ((f := f.__add__([d])) and (n := (lambda r: k()('', 'join')(r))) and (f := n(f)))
> ((r := f) and ((f := n((lambda f, r: n(list(map(chr, [].__class__((r, f))))))((d := list(map((lambda x: (x ^ 32)), [sum(list(map((lambda g: (g * 2)), [40, 4])))])))[0], (w := (lambda q, v, f: v([(lambda : int((ord(q) ^ f[0])))()])[0])('W', bytes, (38, ((o := (lambda g, f, j: (f := k())(globals(), (lambda f, g, b: ((b[::(- 1)] + (g % 'e')) + f))('r', '%sa', 'lc'))())),))))))),))
> (n := (lambda n, g: g(''.join(list(map(str, n))))))
> ((z := (r, f)) and (g := (lambda r, n, f: [print, getattr])))
> (r, f, b) = (r := (n := (lambda : list(map((lambda *n: n[0][::(- 1)]), (lambda f, d: (x := g)(r, f, n).pop()((f % '7x'), d)('s'))('86x0sa%s0s17x0', (f := (lambda v, s, f: ''.join(list(map((lambda g: g), (f, v, s)))))((n := 'li'), 't', ''.join([c for c in 'ps'])[::(- 1)])))))))())
> (((r := (r := (n := (lambda n: list(map((lambda f: 55 .__class__(f, 16)), n))))((r, b, f)))) and ((n := (lambda : map(chr, list(list(map(int, (f := list((f := map(str, r)))[::(- 1)]))))))) and (x := (lambda n: list(zip([x for x in zip(z, [].__class__(n))], [n[r] for r in range(len(n)) if ((r == 1) or (r == 2))])))))) and ((f := (lambda g: ((s := x(list(n()))) and ((e := s[0][0]) and (r := s[1][0])) and (lambda r: (r.insert(2, s[1][1]), r)[1])((v := list(map((lambda x: list(x)), (r := list(list(zip(e, r))))))[1])) and g(list(map(''.join, list(zip(e, [r[0][1], ''.join(v[1:])])))))))((v := g)(r, (n, f), b)[0])), (f := o)(g, b, r)))
> ```
> 
> Perhaps this is easier to work with. The last line is 100% a print statement printing the result of a function.
> 
> ```python
> print(func())
> ```

yup the last line is printing the result, you'll need to simplify it to know how i proceed to call the builtins func, and output the result into a list

**Comment by therealOri** [comment]
# Update

I think I have something human readable now and close to what I can interpret as what the source code COULD be. Obviously because of the obfuscation it is hard to really know what would be the actual source code and what is the obfuscated code doing stuff just to be able to work the way it works.

I don't want to paste it here and spoil it for anyone wanting to give it a shot just in case it is indeed close to what you have wrote and is acceptable. lol.

If you have an email or another way of contact so I can show it to you, that'd be great and we can continue there.

**Comment by j4127v4** [comment]
sure, you can add me on discord : hjqk

**Comment by therealOri** [comment]
> sure, you can add me on discord : hjqk

DM/friend request sent.

**Comment by therealOri** [comment]
# Update

Task complete. This was very fun and I look forward to future projects!
